name: fastlane

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
        with:
          usePlayStoreLocales: true

  validate-no-launcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
        with:
          fastlaneDir: ./app/src/nolauncher/fastlane/metadata/android
          usePlayStoreLocales: true
