name: build

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle
      - uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false
      - name: Prepare release keystore
        run: |
          echo "${{ secrets.RELEASE_STORE_FILE_BASE64 }}" > keystore.jks.asc
          gpg -d --passphrase "${{ secrets.RELEASE_STORE_FILE_PASSPHRASE }}" --batch keystore.jks.asc > app/keystore.jks
      - name: Write secrets to environment
        run: |
          echo "ORG_GRADLE_PROJECT_PRIVATE_DNS_QS_RELEASE_STORE_FILE=keystore.jks" >> "$GITHUB_ENV"
          echo "ORG_GRADLE_PROJECT_PRIVATE_DNS_QS_RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}" >> "$GITHUB_ENV"
          echo "ORG_GRADLE_PROJECT_PRIVATE_DNS_QS_RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}" >> "$GITHUB_ENV"
          echo "ORG_GRADLE_PROJECT_PRIVATE_DNS_QS_RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}" >> "$GITHUB_ENV"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean assembleRelease bundleRelease
      - name: Upload apk/aab
        uses: actions/upload-artifact@v4
        with:
          path: |
            app/build/outputs/apk/**/*-release.apk
            app/build/outputs/bundle/**/*-release.aab
          if-no-files-found: error
