name: build

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

concurrency:
  # Limit concurrency to 1 for PRs. 'main' concurrency isn't limited.
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-build
        with: &setup-build-inputs
          release-keystore: ${{ secrets.RELEASE_STORE_FILE_BASE64 }}
          release-keystore-passphrase: ${{ secrets.RELEASE_STORE_FILE_PASSPHRASE }}
          release-keystore-password: ${{ secrets.RELEASE_STORE_PASSWORD }}
          release-key-alias: ${{ secrets.RELEASE_KEY_ALIAS }}
          release-key-password: ${{ secrets.RELEASE_KEY_PASSWORD }}
      - uses: android-actions/setup-android@v4
        with:
          log-accepted-android-sdk-licenses: false
      - run: ./gradlew lint
      - name: Lint Summary
        uses: hidakatsuya/action-report-android-lint@v1.3.0
        if: always()
        with:
          result-path: 'app/build/reports/**/lint-results-*.xml'

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-build
        with: *setup-build-inputs
      - uses: android-actions/setup-android@v4
        with:
          log-accepted-android-sdk-licenses: false
      - run: ./gradlew test
      - name: Unit tests summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: |
            app/build/test-results/**/TEST-*.xml

  instrumentation-tests:
    name: Instrumentation tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-build
        with: *setup-build-inputs
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 36
          arch: x86_64
          script: ./gradlew connectedAndroidTest
      - name: Instrumentation tests summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: |
            app/build/outputs/androidTest-results/**/TEST-*.xml

  assemble:
    name: Assemble apk/aab
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-build
        with: *setup-build-inputs
      - uses: android-actions/setup-android@v4
        with:
          log-accepted-android-sdk-licenses: false
      - name: Assemble apk/aab
        run: ./gradlew assembleRelease bundleRelease
      - name: Upload apk/aab
        uses: actions/upload-artifact@v7
        with:
          name: artifact
          path: |
            app/build/outputs/apk/**/*-release.apk
            app/build/outputs/bundle/**/*-release.aab
          if-no-files-found: error

  release:
    needs: [lint, unit-tests, instrumentation-tests, assemble]
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: dist
          name: artifact
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            dist/**/*.apk
            dist/**/*.aab
